### ISSUE TITLE
Enable strictBindCallApply in tsconfig.json

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#2690]
Typescript 3.2 added the strictBindCallApply option which checks for incorrect types on various calls.

See [Release Notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html)

Enabling this in Arcs comes up with one failure for FakePecFactory:

```
src/runtime/arc.ts:98:5 - error TS2322: Type '((id: string) => MessagePort) | ((id: string) => PECInnerPort)' is not assignable to type '(id: string) => PECInnerPort'.
  Type '(id: string) => MessagePort' is not assignable to type '(id: string) => PECInnerPort'.
    Type 'MessagePort' is missing the following properties from type 'PECInnerPort': onStop, onDefineHandle, onInstantiateParticle, onUIEvent, and 40 more.

98     this.pecFactory = pecFactory || FakePecFactory(loader).bind(null);
       ~~~~~~~~~~~~~~~
```

**Comment by lindner** [comment]
Assigning to @shans since this typing was introduced in 1725361f5

**Comment by lindner** [comment]
Fixed in 37d366165
