### PR TITLE
Fixes personal cloud build and restores test on Travis

### LINKED ISSUE #4018: Restore bazel tests to Travis when sandbox issue is fixed.
Tracking issue to restore bazel tests to CI on Travis. From chat, ref:

https://travis-ci.org/PolymerLabs/arcs/builds/607924614
https://github.com/microsoft/TypeScript/issues/29221

```
FAIL: //particles/PipeApps:Person_test (see /home/travis/.cache/bazel/_bazel_travis/504270edcd9a48d6d285f3ee471e3abc/execroot/__main__/bazel-out/k8-fastbuild/testlogs/particles/PipeApps/Person_test/test.log)
INFO: From Testing //particles/PipeApps:Person_test:
==================== Test output for //particles/PipeApps:Person_test:
src/tools/dev_server/status-handler.ts(19,17): error TS2742: The inferred type of 'status' cannot be named without a reference to '../../../../../../../../../../../../../../../../build/PolymerLabs/arcs/node_modules/@types/express-serve-static-core/index.js'. This is likely not portable. A type annotation is necessary.
```

General theory is that something with bazel running in a sandbox on Travis breaks symlink references. @cromwellian suggested exploring various relevant flags here:

We tried spawn_strategy but alone it was insufficient https://github.com/PolymerLabs/arcs/pull/4013

Further options:

https://github.com/bazelbuild/sandboxfs/blob/master/INSTALL.md
https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_sandboxfs_map_symlink_targets

### PR DESCRIPTION
**Pull request by csilvestrini**
- Revert tsc version to 3.6.4 for server (we haven't the server code to work with 3.7.2 yet)
- Reverts #4014 (caused error TS7027: Unreachable code detected).
- Restores personal cloud test on Travis (reverts #4024).

Build should be back to normal!

Fixes #4018.

### CODE REVIEW

File: .travis.yml [hunk 1]
```diff
@@ -24,6 +24,8 @@ script:
     //src/...
     //src_kt/...
   - npm run test-with-start
+  - npm run build:rollup
+  - npm --prefix=server test
```
Comment (cromwellian) [inline .travis.yml]: I hope we can eventually shard this out to be tested separately, since it doesn't (?) impact the rest of the codebase.

Comment (shaper) [reply .travis.yml]: server tests have been disabled for the time being.
